version: "2"

services:
  mongodb:
    image: mongo
    container_name: howard_blog_mongodb
    environment: 
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null --quiet
  blog:
    depends_on:
      - mongodb
    build: .
    container_name: blog
    image: howard/blog:latest
    restart: always
    links:
      - howard_blog_mongodb
    environment:
      - VIRTUAL_HOST=www.semimajoraxis.com
      - LETSENCRYPT_HOST=www.semimajoraxis.com
      - LETSENCRYPT_EMAIL=chenhao.w@gmail.com